
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohahqtkbcbtcxidvrqwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYWhxdGtiY2J0Y3hpZHZycXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjY3OTAsImV4cCI6MjA1NjAwMjc5MH0.FSGc6JnH0MnJ_hUVFgUkvrKG4yykm759Q9wy9K1UDSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
